### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by skcksjhcnsk** [PyojinKim/LPIC#1]

**Comment by skcksjhcnsk** [comment]
There has some error when i test your  code on the fr3-nostruc-notex dataset and fr3-longoffice dataset. The error seems to occur when the program reachs the detectOrthogonalLineRANSAC_ODEP, which makes the program unable to run normally. The other five datasets are normaly. If you have time, please help me  solve this problem.

**Comment by PyojinKim** [comment]
> There has some error when i test your code on the fr3-nostruc-notex dataset and fr3-longoffice dataset. The error seems to occur when the program reachs the detectOrthogonalLineRANSAC_ODEP, which makes the program unable to run normally. The other five datasets are normaly. If you have time, please help me solve this problem.

Could you describe the error in a bit more detail? LPIC sometimes cannot run correctly depending on the user-defined parameters such as the maximum line lengths, # of lines, etc.

**Comment by skcksjhcnsk** [comment]
I tried to change the parameters like you said  when i test LPIC on  fr3-nostruc-notex dataset,at first ,it  can run normaly ,but after running about 120 pictures,it kept to prompt me that "Fail 1-line RANSAC,Try again”
![fr3-nostruc-notex](https://user-images.githubusercontent.com/89959593/140241824-57962fac-ecc5-401c-a93e-6c436808f801.jpg)
Here is the dataset:
![fr3-nostruc-notex1](https://user-images.githubusercontent.com/89959593/140257710-dd9465c0-df53-40b7-ba28-16af58abc3cf.jpg)

I also have problem on fr3_longoffice，it stop running at the fourth pictures.
![fr3-longoffice](https://user-images.githubusercontent.com/89959593/140241849-27e8012a-f3df-44fd-a62b-72f81832ff0e.jpg)
Here is the dataset：
![fr3_lonngoffice1](https://user-images.githubusercontent.com/89959593/140257789-c82c4d2a-fbff-4c80-991a-a7a1532e0e37.png)

I don't know how to fix it.If it's convenient for you,please help me.

**Comment by PyojinKim** [comment]
The fr3-nostruc-notex dataset is a very difficult dataset to run stably. I think that LPIC will fail from time to time depending on the user-defined parameters. The main reason why it fails might be the insufficient number of lines following the MW. You know, the LPIC can only work well in the strict MW, so if that assumption is broken, LPIC cannot work at all.

**Comment by PyojinKim** [comment]
If you don't have any further questions, I will close this issue.
