### ISSUE TITLE
The difference between the ICL-NUIM dataset and the TUM RGB-D dataset

### ISSUE THREAD

**Issue by skcksjhcnsk** [PyojinKim/LPIC#2]
When I run the ICL-NUIM dataset using the sample code you provided, there has an  error. I use the camera calibration matrix provided by the ICL-NUIM dataset, but the estimated and true values of yaw and roll are  totally oppositeas as shown in this picture. Do I need to make changes in the code ?
![image](https://user-images.githubusercontent.com/89959593/145385114-069d6642-922d-4552-8c15-6b737b011b26.png)
![image](https://user-images.githubusercontent.com/89959593/145385134-1e1b2652-40eb-4845-a123-d4a2b8c6b444.png)
Given that the sample code you provided runs on the TUM RGB-D dataset, do I have to change some reference values to get the code to run on the ICL NUIM dataset?

**Comment by PyojinKim** [comment]
It looks like the camera body frame axis has been flipped.
Did you check and confirm the camera intrinsic matrix K?
As you know, TUM and ICL have different camera body frames.

**Comment by skcksjhcnsk** [comment]
I don't make any changes in the code expect I replace the previous K with the intrinsic matrix K of the camera provided by the ICL-NUIM dataset because i see that these two datasets are compatible
![image](https://user-images.githubusercontent.com/89959593/145517213-a0ebb84d-6e5f-47bb-86c3-63e52033c2f1.png)

**Comment by PyojinKim** [comment]
Before using the publicly available dataset, you SHOULD figure out the inertial frame and camera body frame first.
In the ICL-NUIM paper, the authors clearly mentioned that POVRay follows a left-handed coordinate system.
If you change the negative sign of the y-axis to the positive, it will solve your problem I guess.

![image](https://user-images.githubusercontent.com/19288158/145518998-d9834c00-b8c1-499f-8fe9-1abc460eb890.png)

**Comment by skcksjhcnsk** [comment]
The problem has been solved just as you said.Thanks very much!
